### ISSUE TITLE
Svelte 5 compatibility

### ISSUE THREAD

**Issue by benkuper** [gira-de/svelte-undo#23]
Hello, and thank you for developing this !
I'm migrating my projects to Svelte 5, but svelte-undo doesn't play nice with it :)
Is this just a dependency declaration or is there an actual problem using it with Svelte 5 ?

**Comment by bztes** [comment]
Maybe just a peer dependency issue. I'll look into it later.

**Comment by bztes** [comment]
What do you mean by 'doesn't play nice with it'? Is it just the npm warning, or is there something else?

**Comment by benkuper** [comment]
Sorry I should have poster this in the first post..

```
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: goldenboard@0.0.1
npm error Found: svelte@5.2.3
npm error node_modules/svelte
npm error   dev svelte@"^5.0.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer svelte@"^3.55.1 || ^4.0.0" from @gira-de/svelte-undo@1.2.2
npm error node_modules/@gira-de/svelte-undo
npm error   dev @gira-de/svelte-undo@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\bkupe\AppData\Local\npm-cache\_logs\2024-11-18T23_07_32_490Z-eresolve-report.txt
npm error A complete log of this run can be found in: C:\Users\bkupe\AppData\Local\npm-cache\_logs\2024-11-18T23_07_32_490Z-debug-0.log
```

**Comment by daniel-albuschat** [comment]
@benkuper Thanks for using svelte-undo, we hope that you have fun with it 🤘
We just released version 1.3.0, which is compatible with svelte 5.0. Feel free to test it, and if you like we'd be glad to hear feedback.

**Comment by benkuper** [comment]
Thank you very much !
Is there some documentation on how to work with Svelte 5 runes like $state ? My whole app is now flowing with them and it would be so great to have seamless integration on that !

**Comment by bztes** [comment]
Currently, only classic Svelte stores are supported. We started experimenting with runes. However it's not ready yet. https://github.com/gira-de/svelte-undo/tree/svelte-5-runes
